// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjnhysbklmdeypokzsxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqbmh5c2JrbG1kZXlwb2t6c3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODUwMjAsImV4cCI6MjA1OTE2MTAyMH0.xqbQRDy0SqhS-5Ll4r8tmAW8oUDXRy2KY6wURU6MFmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
